
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: karpenter-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: karpenter-webhook
      namespace: system
      path: /mutate-karpenter-sh-v1alpha1-scalepolicy
  failurePolicy: Fail
  name: mscalepolicy.kb.io
  rules:
  - apiGroups:
    - karpenter.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalepolicies
