
apiVersion: v1
kind: Service
metadata:
  name: karpenter-webhook-service
  namespace: karpenter-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: karpenter-controller-manager
