apiVersion: karpenter.sh/v1 # eventually move to "autoscaling/v1"
kind: HorizontalAutoscaler
metadata:
  name: capacity-utilization-and-pending-pods
spec:
  nodeSelector: # Migrate this to Cluster API MachineDeployment Object Selector in the future
    eks.amazonaws.com/node-group: node-group-1
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      scalePolicy: Max # selects the policy with the highest possible change.
      stabilizationWindowSeconds: 60 # number of seconds for which past recommendations should be considered
    scaleDown:
      scalePolicy: Disabled # disabled scale down
  metrics:
  - type: Node
    external:
      name: karpenter.sh|metrics|pending-pods
      target:
        type: Value
        value: 0
  - type: Node
    node:
      name: cpu-requests
      target:
        type: AverageUtilization
        averageUtilization: 80
  - type: Node
    node:
      name: memory-requests
      target:
        type: AverageUtilization
        averageUtilization: 80