
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - karpenter.my.domain
  resources:
  - scalepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.my.domain
  resources:
  - scalepolicies/status
  verbs:
  - get
  - patch
  - update
