# permissions for end users to edit scalepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-scalepolicy-editor-role
rules:
- apiGroups:
  - karpenter.sh
  resources:
  - scalepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.sh
  resources:
  - scalepolicies/status
  verbs:
  - get
