apiVersion: autoscaling/v2beta2
kind: ScalePolicy
metadata:
  name: cpu-policy
spec:
  selector:
    "aws/node"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - sqsQueue:
      metric: "message-count"
      # utilization: 50
      value: 3
  - node:
      cpu: 30
      mem: 50
  - type:


---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {scaled-object-name}
spec:
  scaleTargetRef:
    deploymentName: {deployment-name} # must be in the same namespace as the ScaledObject
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.eu-west-1.amazonaws.com/account_id/QueueName
      queueLength: "5"
      awsRegion: "eu-west-1"
      identityOwner: pod | operator # Optional. Default: pod
  - type: utilization
    metadata:
      thresholds:
        cpu: 50
        mem: 50
  - type: unschedulable
    metadata: ...